theme: jekyll-theme-minimal
title: "Dan Fessler"
description: "Senior Software Engineer for Web and Games"
logo: https://avatars.githubusercontent.com/u/1312084?v=4
phone: "760.985.4865"
website: "http://danfessler.com"
email: "Dan@DanFessler.com"
location: "San Francisco, CA"
